---
abstract: 'Calendar view for RT ticket dates and custom fields'
author:
  - 'Best Practical Solutions, LLC'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-Calendar
no_index:
  directory:
    - etc
    - html
    - inc
    - po
    - static
requires:
  DateTime: 0
  DateTime::Set: 0
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '1.10'
x_module_install_rtx_version: '0.43'
x_requires_rt: 5.0.0
